#!/bin/bash

GITUNDERCONTROL=$(git rev-parse --is-inside-work-tree)
GITWORKTREE=$(git rev-parse --show-toplevel)
LINUXWORKTREE=$(echo /$GITWORKTREE|sed 's/://g'|sed 's/\/\//\//g')

GITKEEP='.gitkeep'
GITSHADOWCONFIG='alias'
CONFIGFILE="$LINUXWORKTREE/$GITKEEP/$GITSHADOWCONFIG"

SHADOWREPOLIST=""
SHADOWCONFIGLIST=""

getShadowEnvironment() {

    SHADOWREPOLIST=`find "$LINUXWORKTREE" -type d -maxdepth 1 -name ".git-*" | sed 's/.git-//g' | xargs basename {}`
    if [[ -f $CONFIGFILE ]]; then
        SHADOWCONFIGLIST=$(<"$CONFIGFILE")
    fi

}

# fin
getRepoAlias() {

    echo -e "Shadow repo alias:"
    for repo in $SHADOWREPOLIST; do
        cat "$CONFIGFILE" | xargs -l1 |
        while read -r conf; do
            if [[ $conf == *--git-dir=.git-$repo* ]]; then
                echo $conf
            fi
        done
    done

}

# fin
gitShadowList() {

    if [[ GITUNDERCONTROL ]]; then
        getShadowEnvironment
        getRepoAlias
    else
        echo -e "This folder is not under git control."
    fi

}


# fin
gitShadowCreate() {

    if [[ GITUNDERCONTROL ]]; then
        getShadowEnvironment
        createNewShadowAlias $1 $2
    else
        echo -e "This folder is not under git control."
    fi

}

gitShadowInstall() {

    case `uname` in
        Darwin )
            platform="MacOSX"
            path="/usr/local/bin/"
            ;;
        Linux )
            ;;
        MINGW32_NT-* )
            platform="Windows"
            path="/usr/bin/"
            ;;
    esac
    
    if [[ ! -z "$path" ]]; then
        cp `basename $0` $path
        chmod +x $path/git-shadow
        echo -e "git shadow alias installed."
        printUsage
    fi

}

printUsage() {
    echo -e "usage:"
    echo -e "[create shadow alias] git shadow create <git-repo> <repo-command-alias>"
    echo -e "[load alias]. .gitkeep/alias"
    echo -e "[init <git-repo>]<repo-command-alias> init"
}

# fin
createNewShadowAlias() {
    isFound=false
    checkWorkDirExist $1 $isFound
    checkAliasExist $2 $isFound

    if $isFound ; then
        exit
    fi

    if [[ ! -d $GITKEEP ]] ; then
        mkdir $GITKEEP
    fi

    if [[ ! -f $CONFIGFILE ]] ; then
        touch $CONFIGFILE
    fi

    echo "alias $2='echo copy=$LINUXWORKTREE/$GITKEEP/$1.gitignore;if [[ -f $LINUXWORKTREE/$GITKEEP/$1.gitignore ]]; then cp $LINUXWORKTREE/$GITKEEP/$1.gitignore $LINUXWORKTREE/.gitignore; fi;git --git-dir=.git-$1 --work-tree=. \$1'" >> "$CONFIGFILE"

}

# fin
checkWorkDirExist(){
    # $1 repo
    if $2 ; then
        exit
    fi

    isFound=false
    for repo in $SHADOWREPOLIST; do
        if [[ $repo = "$1" ]]; then
            isFound=true
        fi
    done

    if $isFound ; then
        echo -e "git work-dir:\n.git-$1\existed"
    fi

}

# fin
checkAliasExist(){
    # $1 alias

    if $2 ; then
        exit
    fi

    isFound=false

    for conf in $SHADOWCONFIGLIST; do
        if [[ $conf == *$1=git* ]]; then
            isFound=true
        fi
    done

    if $isFound ; then
        echo -e "git shadow alias:\n$1\existed"
    fi

}


echo -e "Git Shadow Alias 0.1"
if [[ -z "$1" ]]; then
    echo BASH_SOURCE=$BASH_SOURCE
    if [[ "$BASH_SOURCE" = *\.* ]]; then
        #statements
        echo -e "Please install this script first."
        echo -e bash `basename "$0"` install
    else    
        printUsage
    fi
else
    case $1 in
        list )
            gitShadowList
            ;;
        create* )
            gitShadowCreate $2 $3
            ;;
        rebuild )
            gitShadowRebuild
            ;;
        install )
            gitShadowInstall
            ;;
    esac

fi



